version: "2"
services: 
       jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        ports:
         - "8080:8080"
         - "50000:50000"
        volumes:
         # - "$pwd/jenkins_home:/var/jenkins_home"
           - "/var/jenkins_home"
        networks:
          - net
       remote_host:
           container_name: remote_host
           image: remote_host
           build: 
             context: . 
           networks:
              - net 
networks:
     net:  
